### ISSUE TITLE
What is the user value of the "version" property of validation results?

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/gavel.js#173]
I would like to learn more about the `version` property of the validation result, and potentially deprecate it, if it bears no user value.

**Comment by honzajavorek** [comment]
It was there since ever, but my hunch would be that someone needed to change the structure of the validation result with a breaking change. The validation result object was probably stored somewhere (Apiary?), so they needed to distinguish which stored result objects are in the original structure and which ones are in the new structure. Hence they probably added `version: 2` to the new one.

What I write is something I'd expect has happened, from seeing the crime scene, I have no other clues or memories to support the hypothesis. I don't think it has any purpose in current Dredd or Apiary. I don't know exactly how the flow of the validation result in Apiary looks like, we need to reverse-engineer that from reading code.

**Comment by artem-zakharchenko** [comment]
The `version` field is used internally by Apiary during printing of Gavel results. It affects pointers.

**Comment by artem-zakharchenko** [comment]
The `version` property has been removed in the current release (https://github.com/apiaryio/gavel.js/releases/tag/v6.0.0). Please refer to the mentioned changelog to use the latest API of the library.
