### ISSUE TITLE
Using JsonSchema

### ISSUE THREAD

**Issue by VonD** [apiaryio/gavel.js#35]
I'm having trouble using `JsonSchema` : when i use the `validate` method, gavel seems to check for body identity : how can i only validate the schema ?
Is there a reason why the `gavel`main module doesn't export `JsonSchema`?

Many thanks for your help.

**Comment by honzajavorek** [comment]
@netmilk I think Gavel should stay to be a tool to validate HTTP messages. To me, validating the schema seems to be a similar feature request as https://github.com/apiaryio/dredd/issues/462 is for Dredd.

**Comment by artem-zakharchenko** [comment]
Isn't JSON schema parsed/validated during the Gavel's validation by third-party validators?

What is the status of this issue in regards to #90? If we adopt AJV, I expect it to throw upon invalid input. Gavel can handle that exception and, probably, present it in its public API.

**Comment by honzajavorek** [comment]
I think this should be handled by the validator. Gavel checks if JSON Schema is a valid JSON document, but the validator should check whether it is a valid schema document. If it does not (does Amanda do that?), Gavel can use that schema's meta schema to validate whether the document complies with the schema spec. And AFAIK Gavel already does that in some cases, or at least the meta schemas are for some reason part of the package. Since @netmilk's comment is from 2014, my hunch would be this has been implemented, but the issue accidentally wasn't closed.

**Comment by artem-zakharchenko** [comment]
I confirm JSON schemas of V3 and V4 being validated by `tv4` (not Gavel) as a part of `JsonSchema` validator functionality:

https://github.com/apiaryio/gavel.js/blob/2eb036dab59440e2481bff615f5d127df989569a/lib/validators/json-schema.js#L138-L145

> `metaSchema` is derived from the given expected JSON schema, and may be V3 or V4.

I would consider this issue closed.
