### ISSUE TITLE
Install fails in restricted network environment (proxied npm registry)

### ISSUE THREAD

**Issue by lukateake** [apiaryio/gavel.js#83]
Cannot install gavel (as a dependency of dredd) because the `jsonlint` dependency:
https://github.com/apiaryio/gavel.js/blob/master/package.json#L33

Please see this NPM post on how to ameliorate this issue:
http://blog.npmjs.org/post/145724408060/dealing-with-problematic-dependencies-in-a

> It’s usually a good idea to open an issue on the project with the Git dependency, politely asking the maintainers to replace the Git dependency, if possible. Generally, we discourage using Git dependencies in package.json, and it’s typically only used temporarily while a maintainer waits for an upstream fix to be applied and published.

**Comment by honzajavorek** [comment]
@lukateake Thanks for raising this issue. I didn't realise this can be a problem for someone. Just for the record, the dependency isn't taken from npm due to following issues:

- https://github.com/zaach/jsonlint/issues/56
- https://github.com/zaach/jsonlint/compare/master...josdejong:master

I'm open to any suggestions on how to solve this, as well as accepting contributions (replacing the jsonlint library with something else, etc.).

**Comment by honzajavorek** [comment]
Unfortunately, the attempt to replace `jsonlint` with `parse-json` was unsuccessful: https://github.com/apiaryio/gavel.js/pull/85#issuecomment-293985090 Alternative suggestions are welcome.

**Comment by honzajavorek** [comment]
I contacted @josdejong and asked him to publish the fork as a package.

**Comment by honzajavorek** [comment]
This has been just fixed by https://github.com/apiaryio/gavel.js/pull/109! 👏 All praise goes to @abacaphiliac
