### ISSUE TITLE
Gavel.js should print an invalid media type

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/gavel.js#88]
Given API Blueprint like this:

```apib
+ Response 200 (image)
```

Gavel throws an error that the media type is invalid. It would be nice if the error message contains the actual value. Instead of:

```
TypeError: invalid media type
```

there would be:

```
TypeError: invalid media type 'image'
```

**Comment by artem-zakharchenko** [comment]
I assume this error message comes from `mediaTyper` (or similar) library responsible for parsing the given media type. It would be nice for that library to include the raw input in the error message. Perhaps, we can issue a pull request to them.

**Comment by artem-zakharchenko** [comment]
I've issued a pull request into `media-typer` package to improve the returned errors. It's up to the package's maintainers to cooperate on it. Hoping it would get merged.

**Comment by artem-zakharchenko** [comment]
Since there has been no visible progress on this issue in almost a month, I've pinged the `media-typer` library's maintainer to update us on the status. I hope we will get his reply soon.

**Comment by artem-zakharchenko** [comment]
The `media-typer` maintainer did not respond to the pull request, so I suppose we still should cover this under gavel?

**Comment by honzajavorek** [comment]
Yes, we could.

**Comment by artem-zakharchenko** [comment]
Let's analyze where would the users of Gavel experience such error:

1. `mediaTyper.parse()`. During media type parsing it's impossible to propagate the mentioned error to the consumer, since we suppress any exceptions during body media type parsing:

 https://github.com/apiaryio/gavel.js/blob/a6b65a420f855e73e2a75aa1d455f35df191a9c9/lib/units/validateBody.js#L41-L48

2. `mediaTyper.format()`. Formatting is used for error messages when actual body type cannot be validated against the actual body type. In that case such error message must propagate to the end consumer of Gavel.

https://github.com/apiaryio/gavel.js/blob/a6b65a420f855e73e2a75aa1d455f35df191a9c9/lib/units/validateBody.js#L147-L152

Let's analyze each of these two calls of `mediaTyper.format()` in more detail.

* `format(expectedType)`. It can throw here if "Content-Type" header is a malformed string that cannot be parsed. We should add a test for this.
* `format(realType)`. The "Content-Type" header from the actual HTTP message. It's very unlikely for it to be malformed (although possible). I would consider this a corner case.

**Comment by artem-zakharchenko** [comment]
After further investigation, it appears impossible for `expectedType` to be a malformed media type. Elaborating below.

When determining the body type we are using this function:

https://github.com/apiaryio/gavel.js/blob/a6b65a420f855e73e2a75aa1d455f35df191a9c9/lib/units/validateBody.js#L68-L88

In case we have a "Content-Type" header, and it's malformed, this function will go through the `catch` statement, and the "text/plain" media type will be used instead. So, in case of malformed "Content-Type" header Gavel attempts to validate the actual body as plain text.

This being said, the input to `mediaTyper.format()` cannot be malformed. The output from `getBodyType` **is always a valid media type**.

That being said, at the moment I don't see a scenario when Gavel would output the invalid media type where such would be included.

**Comment by artem-zakharchenko** [comment]
Closing this as it's not possible to reach the scenario when `mediaTyper` error would be visible to the end consumer of the library.
